country_mapping = {
    'Afghan': 'Afghanistan',
    'Alandic': 'Aland Islands',
    'Albanian': 'Albania',
    'Algerian': 'Algeria',
    'American Samoan': 'American Samoa',
    'Andorran': 'Andorra',
    'Angolan': 'Angola',
    'Anguillian': 'Anguilla',
    'Barbuda': 'Antigua and Barbuda',
    'Antigua': 'Antigua and Barbuda',
    'Antigua/Barbuda': 'Antigua and Barbuda',
    'Antigua&Barbuda': 'Antigua and Barbuda',
    'Argentinian': 'Argentina',
    'Armenian': 'Armenia',
    'Aruban': 'Aruba',
    'Ascension': 'Ascension Island',
    'Australian': 'Australia',
    'Austrian': 'Austria',
    'Azerbaijani': 'Azerbaijan',
    'Bahamian': 'Bahamas',
    'Bahraini': 'Bahrain',
    'Bangladeshi': 'Bangladesh',
    'Barbadian': 'Barbados',
    'Belarusian': 'Belarus',
    'Belizean': 'Belize',
    'Beninese': 'Benin',
    'Bermudian': 'Bermuda',
    'Bhutanese': 'Bhutan',
    'Citizen of Bonaire, Sint Eustatius and Saba': 'Bonaire, Sint Eustatius and Saba',
    'Bonaire': 'Bonaire, Sint Eustatius and Saba',
    'Saba': 'Bonaire, Sint Eustatius and Saba',
    'Sint Eustatius': 'Bonaire, Sint Eustatius and Saba',
    'Saint Eustatius': 'Bonaire, Sint Eustatius and Saba',
    'St. Eustatius': 'Bonaire, Sint Eustatius and Saba',
    'Bosnian/Herzegovinian': 'Bosnia and Herzegovina',
    'Bosnia': 'Bosnia and Herzegovina',
    'Bosnia & Herzegovina': 'Bosnia and Herzegovina',
    'Bosnia/Herzegovina': 'Bosnia and Herzegovina',
    'Botswanan': 'Botswana',
    'Bouvet': 'Bouvet Island',
    'Brazilian': 'Brazil',
    'Brunei': 'Brunei Darussalam',
    'Bulgarian': 'Bulgaria',
    'Burkinabe': 'Burkina Faso',
    'Burundian': 'Burundi',
    'Cambodian': 'Cambodia',
    'Cameroonian': 'Cameroon',
    'Canadian': 'Canada',
    'Cape Verdean': 'Cape Verde',
    'Cayman': 'Cayman Islands',
    'Central African': 'Central African Republic',
    'Chadian': 'Chad',
    'Chilean': 'Chile',
    'Chinese': 'China',
    'Colombian': 'Colombia',
    'Comoran': 'Comoros',
    'Congolese': 'Congo',
    'Costa Rican': 'Costa Rica',
    'Ivorian': 'Côte d\'Ivoire',
    'Cote d\'Ivoire': 'Côte d\'Ivoire',
    'Cote d Ivoire': 'Côte d\'Ivoire',
    'Croatian': 'Croatia',
    'Cuban': 'Cuba',
    'Curacao': 'Curacao',
    'Cypriot': 'Cyprus',
    'Czech': 'Czech Republic',
    'North Korean': 'Democratic People\'s Republic of Korea (North Korea)',
    'Danish': 'Denmark',
    'Djiboutian': 'Djibouti',
    'Dominican': 'Dominica',
    'Dominican (Dominican Republic)': 'Dominican Republic',
    'Dom Rep': 'Dominican Republic',
    'Ecuadorean': 'Ecuador',
    'Egyptian': 'Egypt',
    'Salvadoran': 'El Salvador',
    'Equatorial Guinean': 'Equatorial Guinea',
    'Eritrean': 'Eritrea',
    'Estonian': 'Estonia',
    'Swazi': 'Eswatini',
    'Ethiopian': 'Ethiopia',
    'Fijian': 'Fiji',
    'Finnish': 'Finland',
    'French': 'France',
    'F. Guiana': 'French Guiana',
    'F. Polynesia': 'French Polynesia',
    'Gabonese': 'Gabon',
    'Gambian': 'Gambia',
    'Georgian': 'Georgia',
    'German': 'Germany',
    'Ghanaian': 'Ghana',
    'Gibraltarian': 'Gibraltar',
    'Greek': 'Greece',
    'Greenlander': 'Greenland',
    'Grenadian': 'Grenada',
    'Guatemalan': 'Guatemala',
    'Guinean': 'Guinea',
    'Guyanese': 'Guyana',
    'Honduran': 'Honduras',
    'Hongkong': 'Hong Kong',
    'Hungarian': 'Hungary',
    'Icelander': 'Iceland',
    'Indian': 'India',
    'Indonesian': 'Indonesia',
    'Iraqi': 'Iraq',
    'Irish': 'Ireland',
    'Iranian': 'Islamic Republic of Iran',
    'Manx': 'Isle Of Man',
    'Israeli': 'Israel',
    'Italian': 'Italy',
    'Jamaican': 'Jamaica',
    'Japanese': 'Japan',
    'Jordanian': 'Jordan',
    'Kazakh': 'Kazakhstan',
    'Kenyan': 'Kenya',
    'I-Kiribati': 'Kiribati',
    'Kuwaiti': 'Kuwait',
    'Kyrgyz': 'Kyrgyzstan',
    'Laos': 'Lao People\'s Democratic Republic',
    'Latvian': 'Latvia',
    'Lebanese': 'Lebanon',
    'Mosotho': 'Lesotho',
    'Liberian': 'Liberia',
    'Libyan': 'Libya',
    'Liechtensteiner': 'Liechtenstein',
    'Lithuanian': 'Lithuania',
    'Luxembourger': 'Luxembourg',
    'Macau': 'Macao',
    'Malagasy': 'Madagascar',
    'Portugal': 'Madeira-Portugal',
    'Malawian': 'Malawi',
    'Malaysian': 'Malaysia',
    'Maldivian': 'Maldives',
    'Malian': 'Mali',
    'Maltese': 'Malta',
    'Marshall I.': 'Marshall Islands',
    'Mauritanian': 'Mauritania',
    'Mauritian': 'Mauritius',
    'Mexican': 'Mexico',
    'Monegasque': 'Monaco',
    'Mongolian': 'Mongolia',
    'Montenegrin': 'Montenegro',
    'Montserratian': 'Montserrat',
    'Moroccan': 'Morocco',
    'Mozambican': 'Mozambique',
    'Namibian': 'Namibia',
    'Nauruan': 'Nauru',
    'Nepalese': 'Nepal',
    'New Zealander': 'New Zealand',
    'Nicaraguan': 'Nicaragua',
    'Nigerien': 'Niger',
    'Nigerian': 'Nigeria',
    'Macedonian': 'North Macedonia',
    'Macedonia': 'North Macedonia',
    'Norwegian': 'Norway',
    'Omani': 'Oman',
    'Pakistani': 'Pakistan',
    'Palauan': 'Palau',
    'Panamanian': 'Panama',
    'Papuan': 'Papua New Guinea',
    'Paraguayan': 'Paraguay',
    'Peruvian': 'Peru',
    'Bolivian': 'Plurinational State of Bolivia',
    'Bolivia': 'Plurinational State of Bolivia',
    'Polish': 'Poland',
    'Portuguese': 'Portugal',
    'Puerto Rican': 'Puerto Rico',
    'Qatari': 'Qatar',
    'Moldovan': 'Republic of Moldova',
    'Moldova': 'Republic of Moldova',
    'Reunionese': 'Reunion',
    'Romanian': 'Romania',
    'Russian': 'Russian Federation',
    'Russia': 'Russian Federation',
    'Rwandan': 'Rwanda',
    'Barthelemois': 'Saint Barthélemy',
    'Saint Helenian': 'Saint Helena, Ascension and Tristan Da Cunha',
    'Kittian/Nevisian': 'Saint Kitts and Nevis',
    'Saint Lucian': 'Saint Lucia',
    'Saint-Martinois': 'Saint Martin (French Part)',
    'Samoan': 'Samoa',
    'Sao Tomean': 'Sao Tome and Principe',
    'Saudi Arabian': 'Saudi Arabia',
    'Senegalese': 'Senegal',
    'Serbian': 'Serbia',
    'Seychellois': 'Seychelles',
    'Sierra Leonean': 'Sierra Leone',
    'Singaporean': 'Singapore',
    'Sint Maartener': 'Sint Maarten (Dutch Part)',
    'Slovak': 'Slovakia',
    'Slovenian': 'Slovenia',
    'Solomon I.': 'Solomon Islands',
    'Somali': 'Somalia',
    'South African': 'South Africa',
    'South Korean': 'South Korea',
    'South Sudanese': 'South Sudan',
    'Spanish': 'Spain',
    'Spain': 'Spain (Canaries)',
    'Sri Lankan': 'Sri Lanka',
    'Palestinia': 'State of Palestine',
    'Sudanese': 'Sudan',
    'Surinamese': 'Suriname',
    'Swedish': 'Sweden',
    'Swiss': 'Switzerland',
    'Syria': 'Syrian Arab Republic',
    'Taiwan': 'Taiwan Province',
    'Tajikistani': 'Tajikistan',
    'Thai': 'Thailand',
    'Congo': 'The Democratic Republic of Congo',
    'Myanmar': 'The Republic of the Union of Myanmar',
    'Burma': 'The Republic of the Union of Myanmar',
    'Timor': 'Timor-Leste',
    'Togolese': 'Togo',
    'Trinidad': 'Trinidad and Tobago',
    'Tobago': 'Trinidad and Tobago',
    'Tunisian': 'Tunisia',
    'Turkish': 'Turkey',
    'Turkmen': 'Turkmenistan',
    'Turks and Caicos': 'Turks and Caicos Islands',
    'Tuvaluan': 'Tuvalu',
    'Ugandan': 'Uganda',
    'Ukrainian': 'Ukraine',
    'UAE': 'United Arab Emirates',
    'U.A.E.': 'United Arab Emirates',
    'UK': 'United Kingdom',
    'Tanzania': 'United Republic of Tanzania',
    'US': 'United States',
    'USA': 'United States',
    'U.S.A.': 'United States',
    'Unknown': 'Unknown',
    'Uruguayan': 'Uruguay',
    'Venezuelan': 'Venezuela',
    'Vietnamese': 'Vietnam',
    'British Virgin Islands': 'Virgin Islands, British',
    'U.S. Virgin Islands': 'Virgin Islands, U.S.',
    'US Virgin Islands': 'Virgin Islands, U.S.',
    'Yemeni': 'Yemen',
    'Zambian': 'Zambia',
    'Zimbabwean': 'Zimbabwe',
    'Russia\nRussia':'Russian Federation',
    'United States of America':'United States'
}
